import type { Settings } from './types'

export const defaultSettings: Settings = {
    interval: 20,
    minuteRoundUp: true,

    mainText: '# This is my main text\n\nWe start at {{starttime}} ({{remaining}} min. left)',
    headerText: 'This is my header',
    footerText: 'This is my footer',

    backgroundImage: '',
    backgroundVideo: 'https://cdn.pixabay.com/video/2023/02/25/152183-802330879_tiny.mp4',
    backgroundColor: '#1e293b',

    color: '#ffffff',
    fontFamily: 'system-ui, sans-serif',
    headerSize: 50,
    footerSize: 40,

    mainColor: '#ffffff',
    headerColor: '#ffffff',
    footerColor: '#ffffff',
    mainFontSize: '',
    headerFontSize: '',
    footerFontSize: '',
    mainFontFamily: '',
    headerFontFamily: '',
    footerFontFamily: '',

    timeoutText: "# This is my timer\n\nWe're starting now!",
    titleText: '',
    playSound: false,

    culture: 'en-US',

    sideNote: 'This is my sidebar\n\nExtra info here.\n\n---\n\nVideo by [bellahu123](https://pixabay.com/users/bellahu123-10783290/) via Pixabay',
}

export const contentPresets = [
    {
        id: 'demo',
        label: '⚙️ Demo / start',
        interval: 20,
        mainText: '# This is my main text\n\nWe start at {{starttime}} ({{remaining}} min. left)',
        headerText: 'This is my header',
        footerText: 'This is my footer',
        timeoutText: '# This is my timer\n\nWe\'re starting now!',
        sideNote: 'This is my sidebar\n\nExtra info here.\n\n---\n\nVideo by [bellahu123](https://pixabay.com/users/bellahu123-10783290/) via Pixabay',
        backgroundImage: '',
        backgroundVideo: 'https://cdn.pixabay.com/video/2023/02/25/152183-802330879_tiny.mp4',
    },
    // --- Breaks ---
    {
        id: 'break-5',
        label: '☕ Break — 5 min',
        interval: 5,
        mainText: '# Short Break\n\nBack at {{starttime}} ({{remaining}} min. left)',
        headerText: '',
        footerText: '',
        timeoutText: "# Let's go!\n\nWe're starting now!",
        sideNote: '',
        backgroundImage: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1920&q=80',
        backgroundVideo: '',
    },
    {
        id: 'break-10',
        label: '☕ Break — 10 min',
        interval: 10,
        mainText: '# Break\n\nBack at {{starttime}} ({{remaining}} min. left)',
        headerText: '',
        footerText: '',
        timeoutText: "# Let's go!\n\nWe're starting now!",
        sideNote: '',
        backgroundImage: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1920&q=80',
        backgroundVideo: '',
    },
    {
        id: 'break-15',
        label: '☕ Break — 15 min',
        interval: 15,
        mainText: '# Break\n\nBack at {{starttime}} ({{remaining}} min. left)',
        headerText: '',
        footerText: '',
        timeoutText: "# Let's go!\n\nWe're starting now!",
        sideNote: '',
        backgroundImage: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1920&q=80',
        backgroundVideo: '',
    },
    // --- Lunch ---
    {
        id: 'lunch-30',
        label: '🍽️ Lunch — 30 min',
        interval: 30,
        mainText: '# Lunch Break\n\nEnjoy your meal!\n\nWe start at {{starttime}} ({{remaining}} min. left)',
        headerText: '',
        footerText: '',
        timeoutText: "# Let's go!\n\nWe're starting now!",
        sideNote: '',
        backgroundImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1920&q=80',
        backgroundVideo: '',
    },
    {
        id: 'lunch',
        label: '🍽️ Lunch — 45 min',
        interval: 45,
        mainText: '# Lunch Break\n\nEnjoy your meal!\n\nWe start at {{starttime}} ({{remaining}} min. left)',
        headerText: '',
        footerText: '',
        timeoutText: "# Let's go!\n\nWe're starting now!",
        sideNote: '',
        backgroundImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1920&q=80',
        backgroundVideo: '',
    },
    {
        id: 'geek-lunch',
        label: '🤓 Geek Lunch — 45 min (hex)',
        interval: 45,
        mainText: '# 🤓 Lunch Break\n\nWe start at {{starttime}} ({{remaining:x}} min. left)',
        headerText: '',
        footerText: '',
        timeoutText: "# 0x0 remaining\n\nWe're starting now!",
        sideNote: '',
        backgroundImage: '',
        backgroundVideo: 'https://cdn.pixabay.com/video/2017/07/23/10878-226635359_large.mp4',
    },
    // --- Exercise ---
    {
        id: 'exercise-5',
        label: '🏃 Exercise — 5 min',
        interval: 5,
        mainText: '# Exercise Break\n\nStretch your legs!\n\nBack at {{starttime}} ({{remaining}} min. left)',
        headerText: '',
        footerText: '',
        timeoutText: "# Let's go!\n\nWe're starting now!",
        sideNote: '',
        backgroundImage: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=1920&q=80',
        backgroundVideo: '',
    },
    {
        id: 'exercise-10',
        label: '🏃 Exercise — 10 min',
        interval: 10,
        mainText: '# Exercise Break\n\nSee you soon!\n\nWe start at {{starttime}} ({{remaining}} min. left)',
        headerText: '',
        footerText: '',
        timeoutText: "# Let's go!\n\nWe're starting now!",
        sideNote: '',
        backgroundImage: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=1920&q=80',
        backgroundVideo: '',
    },
    {
        id: 'exercise-15',
        label: '🏃 Exercise — 15 min',
        interval: 15,
        mainText: '# Exercise Break\n\nSee you soon!\n\nWe start at {{starttime}} ({{remaining}} min. left)',
        headerText: '',
        footerText: '',
        timeoutText: "# Let's go!\n\nWe're starting now!",
        sideNote: '',
        backgroundImage: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=1920&q=80',
        backgroundVideo: '',
    },
    {
        id: 'exercise-20',
        label: '🏃 Exercise — 20 min',
        interval: 20,
        mainText: '# Exercise Break\n\nSee you soon!\n\nWe start at {{starttime}} ({{remaining}} min. left)',
        headerText: '',
        footerText: '',
        timeoutText: "# Let's go!\n\nWe're starting now!",
        sideNote: '',
        backgroundImage: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=1920&q=80',
        backgroundVideo: '',
    },
    {
        id: 'exercise-30',
        label: '🏃 Exercise — 30 min',
        interval: 30,
        mainText: '# Exercise Break\n\nSee you soon!\n\nWe start at {{starttime}} ({{remaining}} min. left)',
        headerText: '',
        footerText: '',
        timeoutText: "# Let's go!\n\nWe're starting now!",
        sideNote: '',
        backgroundImage: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=1920&q=80',
        backgroundVideo: '',
    },
    // --- End of day ---
    {
        id: 'dismissed',
        label: '🎒 Class dismissed — 16:00',
        interval: '16:00',
        mainText: '# Class Dismissed\n\nSee you tomorrow!\n\nDoors open at {{starttime}} ({{remaining}} min. left)',
        headerText: '',
        footerText: '',
        timeoutText: '# Have a great day!\n\nDoors are now open.',
        sideNote: '',
        backgroundImage: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1920&q=80',
        backgroundVideo: '',
    },
    {
        id: 'exam',
        label: '📝 Exam — 60 min',
        interval: 60,
        mainText: '# Exam\n\nPens down at {{starttime}}\n\n{{remaining}} minutes remaining',
        headerText: '',
        footerText: 'Good luck — stay calm, read carefully.',
        timeoutText: '# Time is up!\n\nPlease put your pens down.',
        sideNote: '',
        backgroundImage: 'https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?w=1920&q=80',
        backgroundVideo: '',
    },
]
